init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

environment:
  matrix:
    - R_VERSION: devel
    - R_VERSION: release
    - R_VERSION: 3.2.3
      RTOOLS_VERSION: 33
      CRAN: http://cran.rstudio.com
    - R_VERSION: 3.1.3
      RTOOLS_VERSION: 32
      CRAN: http://cran.rstudio.com

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
